swagger: '2.0'
info:
  description: dll review registry api
  version: 1.0.0
  title: DLL Review Registry
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: jeffreycwitt@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:4567'
basePath: /api/v1
tags:
  - name: hashes
    description: Find reviews about a text
schemes:
  - http
  - https
paths:
  '/text/{hash}':
    get:
      tags:
        - hashes
      summary: Get list of reviews by hash
      description: ''
      produces:
        - text/html
        - application/json
      parameters:
        - in: path
          type: string
          name: hash
          description: hash of reviewed file
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Review'
  '/review/{id}':
    get:
      tags:
        - reviews
      summary: Get list of reviews by hash
      description: ''
      produces:
        - text/html
        - application/json
      parameters:
        - in: path
          type: string
          name: id
          description: short id of review
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Review'
definitions:
  Review:
    type: object
    properties:
      id:
        type: integer
        format: int64
      review-society:
        type: string
        description: ''
      date:
        type: string
        format: date-time
      badge-url:
        type: string
        description: ''
      badge-rubric:
        type: integer
        format: int32
        description: Order Status
      review-report:
        type: string
        description: ''
      review-summary:
        type: string
        description: ''
      sha-256:
        type: string
        description: ''
      ipfs-hash:
        type: string
        description: ''
      git-blob-hash:
        type: string
        description: ''
      url:
        type: string
        description: ''
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about the DLL Review Registry
  url: dll-review-registry.herokuapp.com/about
